import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Healthy Earth",
  description: "Terms of Service for Healthy Earth by BioCare Fertilisers Pty Ltd.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: `By accessing or using the Healthy Earth website (healthyearth.com.au) and any associated services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any part of these terms, you may not use our services.\n\nThese terms apply to all visitors, users, and others who access or use the service. BioCare Fertilisers Pty Ltd reserves the right to update or modify these terms at any time without prior notice. Your continued use of the site following any changes constitutes your acceptance of the revised terms.`,
  },
  {
    title: "2. Use of the Website",
    body: `You agree to use this website only for lawful purposes and in a manner that does not infringe the rights of others or restrict their use and enjoyment of the site. Prohibited uses include:\n\n• Transmitting any unsolicited or unauthorised advertising or promotional material\n• Attempting to gain unauthorised access to any part of the site or its related systems\n• Using the site in any way that could damage, disable, or impair the site's functionality\n• Scraping, data-mining, or harvesting content without written permission\n• Uploading or transmitting viruses or any other malicious code\n\nWe reserve the right to terminate or restrict access to the site for any user who violates these terms.`,
  },
  {
    title: "3. Product Information & Accuracy",
    body: `We endeavour to ensure that all product descriptions, formulas, application rates and recommendations on this website are accurate and up to date. However, we do not warrant that product information is error-free, complete or current.\n\nProduct formulations, availability and pricing are subject to change without notice. Always refer to the current product label and Safety Data Sheet (SDS) before use. If you identify any inaccuracy, please contact us at info@healthy-earth.com.`,
  },
  {
    title: "4. Ella — AI Plant Nutrition Advisor",
    body: `The "Ella" AI chat feature is provided as a general guidance tool only. Responses generated by Ella are based on general agronomic knowledge and are not a substitute for professional agricultural advice tailored to your specific soil, climate, crop or circumstances.\n\nBioCare Fertilisers Pty Ltd makes no warranties regarding the accuracy, completeness or suitability of recommendations provided by Ella. You should always:\n\n• Read and follow the directions on the relevant product label\n• Conduct a small test application before broad-scale use\n• Consult a qualified agronomist or horticulturalist for complex or high-value situations\n\nUse of Ella is entirely at your own risk. We accept no liability for any loss, damage or adverse outcomes arising from reliance on Ella's recommendations.`,
  },
  {
    title: "5. Intellectual Property",
    body: `All content on this website — including text, graphics, logos, product names, formulations, images and software — is the property of BioCare Fertilisers Pty Ltd or its content suppliers and is protected by Australian and international intellectual property laws.\n\nYou may not reproduce, distribute, modify, transmit or use any content from this site for commercial purposes without our express written permission. Personal, non-commercial use is permitted provided you retain all copyright and proprietary notices.`,
  },
  {
    title: "6. Purchases & Orders",
    body: `Where products are available for purchase through this website or through authorised retailers, all sales are subject to the following:\n\n• Prices are displayed in Australian Dollars (AUD) and include GST where applicable\n• Product availability is subject to change without notice\n• We reserve the right to refuse or cancel any order at our discretion\n• Returns and refunds are handled in accordance with Australian Consumer Law\n\nFor wholesale or trade enquiries, please contact us directly at info@healthy-earth.com.`,
  },
  {
    title: "7. Limitation of Liability",
    body: `To the maximum extent permitted by law, BioCare Fertilisers Pty Ltd and its directors, employees and agents shall not be liable for any direct, indirect, incidental, special or consequential damages arising from:\n\n• Use of or inability to use this website or its services\n• Reliance on product information, recommendations or advice provided on this site\n• Errors, omissions or inaccuracies in site content\n• Unauthorised access to or alteration of your data\n\nNothing in these terms limits or excludes any rights or guarantees you may have under the Australian Consumer Law that cannot lawfully be excluded.`,
  },
  {
    title: "8. Third-Party Links",
    body: `This website may contain links to third-party websites, including stockist and retailer sites. These links are provided for your convenience only. We have no control over the content of those sites and accept no responsibility for them or for any loss or damage that may arise from your use of them.\n\nInclusion of any link does not imply endorsement by Healthy Earth or BioCare Fertilisers Pty Ltd.`,
  },
  {
    title: "9. Privacy",
    body: `Your use of this website is also governed by our Privacy Policy, which is incorporated into these Terms of Service by reference. By using this site, you consent to the collection and use of your information as described in our Privacy Policy.\n\nWe do not sell your personal information to third parties. Any personal information collected is used solely for the purpose of providing our services and improving your experience.`,
  },
  {
    title: "10. Governing Law",
    body: `These Terms of Service are governed by and construed in accordance with the laws of New South Wales, Australia. Any disputes arising under or in connection with these terms shall be subject to the exclusive jurisdiction of the courts of New South Wales.\n\nIf any provision of these terms is found to be unenforceable, the remaining provisions will continue in full force and effect.`,
  },
  {
    title: "11. Contact Us",
    body: `If you have any questions about these Terms of Service, please contact us:\n\nBioCare Fertilisers Pty Ltd\nNew South Wales, Australia\nEmail: info@healthy-earth.com\nPhone: 1800 HEALTHY (Mon–Fri, 8am–5pm AEST)`,
  },
];

export default function TermsPage() {
  return (
    <>
      {/* Hero */}
      <section style={{ background: "#f5f0e8" }} className="pt-16 pb-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-xs font-semibold tracking-widest uppercase mb-4" style={{ color: "#2d7a3a" }}>
            Legal
          </p>
          <h1 className="font-bold text-gray-900 mb-4" style={{ fontSize: "clamp(2rem, 4vw, 3rem)", lineHeight: 1.1 }}>
            Terms of Service
          </h1>
          <p className="text-gray-500 text-sm">
            Last updated: 1 January 2026 · BioCare Fertilisers Pty Ltd
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row gap-12">

            {/* Table of contents */}
            <aside className="lg:w-56 flex-shrink-0">
              <div className="sticky top-24">
                <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-4">Contents</p>
                <nav className="space-y-1">
                  {sections.map((s) => (
                    <a
                      key={s.title}
                      href={`#${s.title.replace(/\s+/g, "-").toLowerCase()}`}
                      className="block text-sm text-gray-500 hover:text-green-700 py-1 leading-snug transition-colors"
                    >
                      {s.title}
                    </a>
                  ))}
                </nav>
              </div>
            </aside>

            {/* Sections */}
            <div className="flex-1 min-w-0 space-y-10">
              <p className="text-gray-600 leading-relaxed text-sm border-l-4 pl-4 py-1" style={{ borderColor: "#2d7a3a", background: "#f0faf2" }}>
                Please read these Terms of Service carefully before using Healthy Earth products, services or this website. These terms form a legally binding agreement between you and BioCare Fertilisers Pty Ltd.
              </p>

              {sections.map((s) => (
                <div key={s.title} id={s.title.replace(/\s+/g, "-").toLowerCase()}>
                  <h2 className="text-lg font-bold text-gray-900 mb-3">{s.title}</h2>
                  <div className="space-y-3">
                    {s.body.split("\n\n").map((para, i) => {
                      if (para.startsWith("•")) {
                        return (
                          <ul key={i} className="space-y-1.5 ml-1">
                            {para.split("\n").map((line, j) => (
                              <li key={j} className="flex gap-2 text-sm text-gray-600 leading-relaxed">
                                <span className="text-green-600 flex-shrink-0 mt-0.5">›</span>
                                <span>{line.replace(/^•\s*/, "")}</span>
                              </li>
                            ))}
                          </ul>
                        );
                      }
                      return (
                        <p key={i} className="text-sm text-gray-600 leading-relaxed">
                          {para}
                        </p>
                      );
                    })}
                  </div>
                </div>
              ))}

              <div className="pt-6 border-t border-gray-100">
                <p className="text-xs text-gray-400">
                  © 2026 Healthy Earth · BioCare Fertilisers Pty Ltd. All rights reserved.{" "}
                  <Link href="/privacy" className="underline hover:text-gray-600 transition-colors">Privacy Policy</Link>
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
